# Generated by Django 3.1.5 on 2021-04-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eppn', models.CharField(blank=True, max_length=255, null=True)),
                ('firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('firstnameOverride', models.CharField(blank=True, max_length=255, null=True)),
                ('lastnameOverride', models.CharField(blank=True, max_length=255, null=True)),
                ('locationOverride', models.CharField(blank=True, max_length=255, null=True)),
                ('fullnameOverride', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
